### ISSUE TITLE
author_names = article.find("sourcedesc").findAll("persname") AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by gnillling** [liuyixin-louis/OpenChatPaper#16]

**Comment by chaosuper68** [comment]
me  too，feel like that problem is related to pdf file parsing

**Comment by chaosuper68** [comment]
pdf没有parse成功，有可能是前端、后端、pdf解析三个服务中间没有连接成功，对于我来说，因为后端huggingface连接需要科学上网，需要代理，导致http连接使用代理，使用代理后本地服务没法连接成功，所以解决方法是：关闭代理，后端服务使用国内镜像
HF_ENDPOINT=https://hf-mirror.com/ python backend.py --port 5000 --host localhost 

同时，需要将flask app的debug改成False
