### ISSUE TITLE
How to command bash serve_grobid.sh in windows env

### ISSUE THREAD

**Issue by tianyang1027** [liuyixin-louis/OpenChatPaper#3]
![image](https://user-images.githubusercontent.com/7963894/227392919-08fb8518-d040-4717-afd1-331c7c38d8c1.png)

**Comment by liuyixin-louis** [comment]
You might consider downloading GitHub bash.

**Comment by tianyang1027** [comment]
![image](https://user-images.githubusercontent.com/7963894/227408880-a1868cda-13d2-481a-8241-4592be15f877.png)

**Comment by tianyang1027** [comment]
```bash
bash serve_grobid.sh
```

**Comment by tianyang1027** [comment]
![image](https://user-images.githubusercontent.com/7963894/227436509-37c2ecc4-b549-4afc-b52e-23399d26ffb9.png)
![image](https://user-images.githubusercontent.com/7963894/227436679-782323f8-d4dc-47f4-b3dd-02cd9a728943.png)
The downloaded zip file name should be grobid-${GROBID_VERSION}

**Comment by liuyixin-louis** [comment]
Cool, I will fix it : ). Thank you
