### ISSUE TITLE
Stuck at step 2. Setup GROBID local server

### ISSUE THREAD

**Issue by MathiasSong** [liuyixin-louis/OpenChatPaper#5]
Hello, 

I am trying to run your program at WSL Ubuntu on Windows 10. 
I am stuck at the step 2. Setup GROBID local server. 
As below it stops at 87% EXECUTING. 
The time increases without updating any. 
Would you please help me out? 

`
1.8.0_362-8u362-ga-0ubuntu1~20.04.1-b09
WARN  [2023-03-28 06:13:34,199] org.glassfish.jersey.internal.inject.Providers: A provider org.grobid.service.exceptions.mapper.GrobidExceptionsTranslationUtility registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.grobid.service.exceptions.mapper.GrobidExceptionsTranslationUtility will be ignored.
INFO  [2023-03-28 06:13:35,129] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    POST    /api/annotatePDF (org.grobid.service.GrobidRestService)
    POST    /api/citationPatentAnnotations (org.grobid.service.GrobidRestService)
    GET     /api/grobid (org.grobid.service.GrobidRestService)
    GET     /api/health (org.grobid.service.resources.HealthResource)
    GET     /api/isalive (org.grobid.service.GrobidRestService)
    POST    /api/processAffiliations (org.grobid.service.GrobidRestService)
    PUT     /api/processAffiliations (org.grobid.service.GrobidRestService)
    POST    /api/processCitation (org.grobid.service.GrobidRestService)
    PUT     /api/processCitation (org.grobid.service.GrobidRestService)
    POST    /api/processCitationNames (org.grobid.service.GrobidRestService)
    PUT     /api/processCitationNames (org.grobid.service.GrobidRestService)
    POST    /api/processCitationPatentPDF (org.grobid.service.GrobidRestService)
    POST    /api/processCitationPatentST36 (org.grobid.service.GrobidRestService)
    POST    /api/processCitationPatentTXT (org.grobid.service.GrobidRestService)
    POST    /api/processDate (org.grobid.service.GrobidRestService)
    PUT     /api/processDate (org.grobid.service.GrobidRestService)
    POST    /api/processFulltextAssetDocument (org.grobid.service.GrobidRestService)
    PUT     /api/processFulltextAssetDocument (org.grobid.service.GrobidRestService)
    POST    /api/processFulltextDocument (org.grobid.service.GrobidRestService)
    PUT     /api/processFulltextDocument (org.grobid.service.GrobidRestService)
    POST    /api/processHeaderDocument (org.grobid.service.GrobidRestService)
<===========--> 87% EXECUTING [4m 28s]
    POST    /api/processHeaderNames (org.grobid.service.GrobidRestService)
    PUT     /api/processHeaderNames (org.grobid.service.GrobidRestService)
    POST    /api/processReferences (org.grobid.service.GrobidRestService)
    PUT     /api/processReferences (org.grobid.service.GrobidRestService)
    POST    /api/referenceAnnotations (org.grobid.service.GrobidRestService)
    GET     /api/version (org.grobid.service.GrobidRestService)

INFO  [2023-03-28 06:13:35,150] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@3e9beef2{/,null,AVAILABLE}
INFO  [2023-03-28 06:13:35,170] io.dropwizard.setup.AdminEnvironment: tasks =

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

INFO  [2023-03-28 06:13:35,191] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@722531ab{/,null,AVAILABLE}
INFO  [2023-03-28 06:13:35,235] org.eclipse.jetty.server.AbstractConnector: Started application@6fc0bbc6{HTTP/1.1,[http/1.1]}{0.0.0.0:8070}
INFO  [2023-03-28 06:13:35,251] org.eclipse.jetty.server.AbstractConnector: Started admin@706ddbc8{HTTP/1.1,[http/1.1]}{0.0.0.0:8071}
INFO  [2023-03-28 06:13:35,252] org.eclipse.jetty.server.Server: Started @13996ms
<===========--> 87% EXECUTING [23s]
> :grobid-service:run
`

**Comment by liuyixin-louis** [comment]
This indicates that you successfully launch the Grobid service. So you can process to step 3 after running this service. Sorry for misleading you, I will polish the documents.
