### ISSUE TITLE
Found error

### ISSUE THREAD

**Issue by Gouryella** [liuyixin-louis/OpenChatPaper#8]
When I use it, an error occurs: "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)".

**Comment by liuyixin-louis** [comment]
Please provide me with more error messages.

**Comment by yippp** [comment]
I met the same problem

the log is 
`  File "G:\GitHub\OpenChatPaper\scipdf_utils.py", line 107, in parse_authors
    author_names = article.find("sourcedesc").findAll("persname")
`

It seems taht it does not consider the case that cannot find the author information

**Comment by Gouryella** [comment]
> Please provide me with more error messages.

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback:
File "/root/miniconda3/envs/tool/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/root/OpenChatPaper/frontend.py", line 100, in <module>
    output = response.json()
File "/root/miniconda3/envs/tool/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

**Comment by liuyixin-louis** [comment]
I will recommend using the docker version instead: https://huggingface.co/spaces/yixin6178/ChatPaper . I think it can make setup way easier.
