### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MathiasSong** [liuyixin-louis/OpenChatPaper#9]
I am sorry to keep asking. 
I followed all the instructions, but I still get the same error. 
For some reason I cannot find the model 'embedding_cache_distiluse-base-multilingual-cased-v2.pkl' from anywhere in my local machine. I also do not find the ckpt folder from anywhere. 

Could you please specify which step I was supposed to set up the model? 

I have been trying to run this in WSL, as well as Windows 10 on the Python 3.9 virtual environment. 

---------------------------------------------
Traceback (most recent call last):
  File "/home/matt_song/projects/OpenChatPaper/backend.py", line 12, in <module>
    embedding_model = HuggingfaceSentenceTransformerModel()
  File "/home/matt_song/projects/OpenChatPaper/embedding_model.py", line 15, in __init__
    super().__init__(model_name)
  File "/home/matt_song/projects/OpenChatPaper/base_class.py", line 33, in __init__
    with open(embedding_cache_path, "wb") as embedding_cache_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/matt_song/ckpt/embedding_cache_distiluse-base-multilingual-cased-v2.pkl'

**Comment by liuyixin-louis** [comment]
Please use the latest code. This problem should be resolved now.
